### ISSUE TITLE
ValueError: Cannot take a larger sample than population when 'replace=False'

### ISSUE THREAD

**Issue by monkeycc** [aartighatkesar/Image-Mosaicing#9]
img
2750*160000

python image_mosaic.py

```
 #### Processing 1.jpg & 2.jpg ######
N: 1122.0, n: 6, M:2.0, p: 0.99, eps: 0.6, delta: 3
Traceback (most recent call last):
  File "image_mosaic.py", line 222, in <module>
    obj.mosaic()
  File "image_mosaic.py", line 40, in mosaic
    inliers_cnt, inliers, outliers, sample_pts, final_H = ransac_obj.run_ransac(correspondence)
  File "D:\Image-Mosaicing\ransac.py", line 115, in run_ransac
    idx, n_idx = self.sample_n_datapts(n_total, self.n)
  File "D:\Image-Mosaicing\ransac.py", line 47, in sample_n_datapts
    idx = np.random.choice(n_total, n, replace=False)
  File "mtrand.pyx", line 954, in numpy.random.mtrand.RandomState.choice
ValueError: Cannot take a larger sample than population when 'replace=False'
```

'replace=True'

python image_mosaic.py

```
 #### Processing 1.jpg & 2.jpg ######
N: 1122.0, n: 6, M:2.0, p: 0.99, eps: 0.6, delta: 3
prev_inlier_cnt: 0, new_inlier_cnt: 0
 Done 0/1122.0
prev_inlier_cnt: 0, new_inlier_cnt: 0
 Done 1/1122.0
prev_inlier_cnt: 0, new_inlier_cnt: 0
 Done 2/1122.0
prev_inlier_cnt: 0, new_inlier_cnt: 0
 Done 3/1122.0
....

prev_inlier_cnt: 0, new_inlier_cnt: 0
 Done 1077/1122.0
prev_inlier_cnt: 0, new_inlier_cnt: 0
 Done 1078/1122.0
prev_inlier_cnt: 0, new_inlier_cnt: 0
 Done 1079/1122.0
prev_inlier_cnt: 0, new_inlier_cnt: 0
 Done 1080/1122.0
prev_inlier_cnt: 0, new_inlier_cnt: 0
 Done 1081/1122.0
prev_inlier_cnt: 0, new_inlier_cnt: 0
 Done 1082/1122.0
prev_inlier_cnt: 0, new_inlier_cnt: 0
 Done 1083/1122.0
prev_inlier_cnt: 0, new_inlier_cnt: 0
 Done 1084/1122.0
prev_inlier_cnt: 0, new_inlier_cnt: 0
 Done 1085/1122.0
prev_inlier_cnt: 0, new_inlier_cnt: 0
 Done 1086/1122.0
prev_inlier_cnt: 0, new_inlier_cnt: 0
 Done 1087/1122.0
prev_inlier_cnt: 0, new_inlier_cnt: 0
 Done 1088/1122.0
prev_inlier_cnt: 0, new_inlier_cnt: 0
 Done 1089/1122.0
prev_inlier_cnt: 0, new_inlier_cnt: 0
 Done 1090/1122.0
prev_inlier_cnt: 0, new_inlier_cnt: 0
 Done 1091/1122.0
prev_inlier_cnt: 0, new_inlier_cnt: 0
 Done 1092/1122.0
prev_inlier_cnt: 0, new_inlier_cnt: 0
 Done 1093/1122.0
prev_inlier_cnt: 0, new_inlier_cnt: 0
 Done 1094/1122.0
prev_inlier_cnt: 0, new_inlier_cnt: 0
 Done 1095/1122.0
prev_inlier_cnt: 0, new_inlier_cnt: 0
 Done 1096/1122.0
prev_inlier_cnt: 0, new_inlier_cnt: 0
 Done 1097/1122.0
prev_inlier_cnt: 0, new_inlier_cnt: 0
 Done 1098/1122.0
prev_inlier_cnt: 0, new_inlier_cnt: 0
 Done 1099/1122.0
prev_inlier_cnt: 0, new_inlier_cnt: 0
 Done 1100/1122.0
prev_inlier_cnt: 0, new_inlier_cnt: 0
 Done 1101/1122.0
prev_inlier_cnt: 0, new_inlier_cnt: 0
 Done 1102/1122.0
prev_inlier_cnt: 0, new_inlier_cnt: 0
 Done 1103/1122.0
prev_inlier_cnt: 0, new_inlier_cnt: 0
 Done 1104/1122.0
prev_inlier_cnt: 0, new_inlier_cnt: 0
 Done 1105/1122.0
prev_inlier_cnt: 0, new_inlier_cnt: 0
 Done 1106/1122.0
prev_inlier_cnt: 0, new_inlier_cnt: 0
 Done 1107/1122.0
prev_inlier_cnt: 0, new_inlier_cnt: 0
 Done 1108/1122.0
prev_inlier_cnt: 0, new_inlier_cnt: 0
 Done 1109/1122.0
prev_inlier_cnt: 0, new_inlier_cnt: 0
 Done 1110/1122.0
prev_inlier_cnt: 0, new_inlier_cnt: 0
 Done 1111/1122.0
prev_inlier_cnt: 0, new_inlier_cnt: 0
 Done 1112/1122.0
prev_inlier_cnt: 0, new_inlier_cnt: 0
 Done 1113/1122.0
prev_inlier_cnt: 0, new_inlier_cnt: 0
 Done 1114/1122.0
prev_inlier_cnt: 0, new_inlier_cnt: 0
 Done 1115/1122.0
prev_inlier_cnt: 0, new_inlier_cnt: 0
 Done 1116/1122.0
prev_inlier_cnt: 0, new_inlier_cnt: 0
 Done 1117/1122.0
prev_inlier_cnt: 0, new_inlier_cnt: 0
 Done 1118/1122.0
prev_inlier_cnt: 0, new_inlier_cnt: 0
 Done 1119/1122.0
prev_inlier_cnt: 0, new_inlier_cnt: 0
 Done 1120/1122.0
prev_inlier_cnt: 0, new_inlier_cnt: 0
 Done 1121/1122.0
prev_inlier_cnt: 0, new_inlier_cnt: 0
 Done 1122/1122.0
Traceback (most recent call last):
  File "image_mosaic.py", line 222, in <module>
    obj.mosaic()
  File "image_mosaic.py", line 40, in mosaic
    inliers_cnt, inliers, outliers, sample_pts, final_H = ransac_obj.run_ransac(correspondence)
  File "D:\Image-Mosaicing\ransac.py", line 142, in run_ransac
    final_H = calculate_homography(in_pts=final_corr_points[:, 2:],
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
```

**Comment by Neo-manchester** [comment]
Yeah me too, I got the same issue..
